services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]